name: Build CarTube into an IPA file

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Run build script
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Caching brew dependencies
        id: brew_cache
        uses: tecolicom/actions-use-homebrew-tools@v1.2
        with:
          tools: ldid
          cache: yes

      - name: Install Dependencies
        if: steps.brew_cache.outputs.cache-hit != 'true'
        run: brew install ldid
      
      - name: Run build script
        run: |
          ./ipabuild.sh
      
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: CarTube
          path: build/CarTube.ipa
          if-no-files-found: error
